[variables]
PYTHON_VERSION = "3.11"

[providers]
providers = ["nodejs", "python"]

[phases.setup]
nixPkgs = ["python311", "nodejs_20"]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = [
    "cd frontend && npm install",
    "cd frontend && npm run build"
]

[start]
cmd = "cd frontend && npm start"
