[variables]
PYTHON_VERSION = "3.11"

[phases.setup]
nixPkgs = ["nodejs_20"]
cmds = []

[phases.build]
cmds = [
    "cd frontend && npm install",
    "cd frontend && npm run build"
]

[start]
cmd = "cd frontend && npm start"
