# Generated by Django 5.1.6 on 2025-05-09 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='logo',
        ),
        migrations.AddField(
            model_name='developer',
            name='logo_url',
            field=models.URLField(blank=True, help_text='Full https:// link to the logo image hosted in your S3 bucket.', max_length=500, null=True),
        ),
    ]
