# Generated by Django 5.1.6 on 2025-05-11 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_project_images_project_image_url_projectimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectimage',
            options={'ordering': ['position']},
        ),
    ]
