# Generated by Django 5.1.6 on 2025-05-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_remove_project_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='main_image_url',
            field=models.URLField(blank=True, help_text='Main image URL for list view (shown on project card).', null=True),
        ),
    ]
