# Generated by Django 5.1.6 on 2025-07-11 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_project_main_image_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartment',
            options={'ordering': ['floor', 'apartment_number']},
        ),
        migrations.AddField(
            model_name='apartment',
            name='apartment_number',
            field=models.CharField(blank=True, help_text='Номер квартиры (например, 42, 12А)', max_length=10),
        ),
        migrations.AddField(
            model_name='apartment',
            name='status',
            field=models.CharField(choices=[('available', 'В наличии'), ('reserved', 'Забронирована'), ('sold', 'Продана')], default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True, help_text='Подробное описание проекта', null=True),
        ),
    ]
