# Generated by Django 5.1.6 on 2025-10-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_apartment_options_apartment_apartment_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Номер телефона или WhatsApp для связи', max_length=32, null=True),
        ),
    ]
