# Generated by Django 4.2.19 on 2026-02-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_apartment_options_apartment_apartment_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='logo',
            field=models.ImageField(blank=True, help_text='Загрузить логотип (автоматически уйдёт на S3)', null=True, upload_to='developers/logos/'),
        ),
        migrations.AddField(
            model_name='project',
            name='main_image',
            field=models.ImageField(blank=True, help_text='Загрузить главное фото проекта', null=True, upload_to='projects/main/'),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузить фото для галереи', null=True, upload_to='projects/gallery/'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='logo_url',
            field=models.URLField(blank=True, help_text='URL логотипа (для старых записей)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='main_image_url',
            field=models.URLField(blank=True, help_text='URL главного фото (для старых записей)', null=True),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='url',
            field=models.URLField(blank=True, verbose_name='S3 URL'),
        ),
    ]
