# Generated by Django 5.1.6 on 2025-10-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_developer_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Одобрено ли модератором (показывается на сайте)'),
        ),
        migrations.AddField(
            model_name='developer',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
