# Generated by Django 5.1.6 on 2026-07-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_apartment_is_approved_developer_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='floor',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
