# Generated by Django 5.1.6 on 2026-07-29 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_add_image_upload_fields'),
        ('backend', '0010_alter_apartment_floor'),
    ]

    operations = [
    ]
