# Generated by Django 5.1.6 on 2026-08-20 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Название')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'ЖК',
                'verbose_name_plural': 'ЖК',
                'ordering': ['position', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Название')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Состояние',
                'verbose_name_plural': 'Состояния',
                'ordering': ['position', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Название')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Район',
                'verbose_name_plural': 'Районы',
                'ordering': ['position', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ListingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Название')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Статус объекта',
                'verbose_name_plural': 'Статусы объектов',
                'ordering': ['position', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Название')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Тип объекта',
                'verbose_name_plural': 'Типы объектов',
                'ordering': ['position', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Название')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Серия дома',
                'verbose_name_plural': 'Серии домов',
                'ordering': ['position', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=160, verbose_name='ФИО')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Телефон')),
                ('is_active', models.BooleanField(default=True, verbose_name='Работает')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Агент',
                'verbose_name_plural': 'Агенты',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_type', models.CharField(choices=[('sale', 'Продажа'), ('rent', 'Аренда')], db_index=True, default='sale', max_length=8, verbose_name='Тип сделки')),
                ('rooms', models.PositiveSmallIntegerField(blank=True, help_text='0 — студия', null=True, verbose_name='Комнат')),
                ('floor', models.SmallIntegerField(blank=True, null=True, verbose_name='Этаж')),
                ('total_floors', models.SmallIntegerField(blank=True, null=True, verbose_name='Этажность')),
                ('area_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Площадь, м²')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена')),
                ('currency', models.CharField(choices=[('USD', '$'), ('KGS', 'сом')], default='USD', max_length=3, verbose_name='Валюта')),
                ('landmark', models.CharField(blank=True, max_length=255, verbose_name='Ориентир')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('owner_phone', models.CharField(blank=True, max_length=32, verbose_name='Телефон собственника')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Точный адрес')),
                ('internal_note', models.TextField(blank=True, verbose_name='Внутренняя заметка')),
                ('is_urgent', models.BooleanField(default=False, verbose_name='Срочно')),
                ('is_exclusive', models.BooleanField(default=False, verbose_name='Эксклюзив')),
                ('is_alternative', models.BooleanField(default=False, verbose_name='Альтернатива')),
                ('is_barter', models.BooleanField(default=False, verbose_name='Бартер')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Удалён')),
                ('complex', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='agency.complex', verbose_name='ЖК')),
                ('condition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='agency.condition', verbose_name='Состояние')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_listings', to=settings.AUTH_USER_MODEL, verbose_name='Кем создан')),
                ('curator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='agency.agent', verbose_name='Куратор')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_listings', to=settings.AUTH_USER_MODEL, verbose_name='Кем удалён')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='agency.district', verbose_name='Район')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='agency.listingstatus', verbose_name='Статус')),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='agency.propertytype', verbose_name='Тип объекта')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='agency.series', verbose_name='Серия')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=160, verbose_name='Клиент')),
                ('deal_date', models.DateField(verbose_name='Дата сделки')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма сделки')),
                ('commission', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Комиссия')),
                ('currency', models.CharField(choices=[('USD', '$'), ('KGS', 'сом')], default='USD', max_length=3, verbose_name='Валюта')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачен')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('curator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='agency.agent', verbose_name='Куратор')),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='agency.listing', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Счёт',
                'verbose_name_plural': 'Счета',
                'ordering': ['-deal_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='agency/listings/', verbose_name='Фото')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='agency.listing', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Фото объекта',
                'verbose_name_plural': 'Фото объектов',
                'ordering': ['position', 'id'],
            },
        ),
    ]
