# Generated by Django 5.1.6 on 2026-08-20 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_seed_dictionaries'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Название')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Этап',
                'verbose_name_plural': 'Этапы',
                'ordering': ['position', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Название')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['position', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FurnitureOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Название')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Мебель',
                'verbose_name_plural': 'Варианты мебели',
                'ordering': ['position', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Heating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Название')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Отопление',
                'verbose_name_plural': 'Виды отопления',
                'ordering': ['position', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Название')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Линия',
                'verbose_name_plural': 'Линии',
                'ordering': ['position', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Название')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Условие расчёта',
                'verbose_name_plural': 'Условия расчёта',
                'ordering': ['position', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sewerage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Название')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Канализация',
                'verbose_name_plural': 'Виды канализации',
                'ordering': ['position', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WallMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Название')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Материал стен',
                'verbose_name_plural': 'Материалы стен',
                'ordering': ['position', 'name'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='agent',
            name='telegram',
            field=models.CharField(blank=True, help_text='Ник без @ или ссылка', max_length=64, verbose_name='Telegram'),
        ),
        migrations.AddField(
            model_name='agent',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Номер для ссылки wa.me. Пусто — берём телефон.', max_length=32, verbose_name='WhatsApp'),
        ),
        migrations.AddField(
            model_name='listing',
            name='built_date',
            field=models.DateField(blank=True, null=True, verbose_name='Год постройки по техпаспорту'),
        ),
        migrations.AddField(
            model_name='listing',
            name='has_electricity',
            field=models.BooleanField(blank=True, null=True, verbose_name='Электричество'),
        ),
        migrations.AddField(
            model_name='listing',
            name='has_gas',
            field=models.BooleanField(blank=True, null=True, verbose_name='Газ'),
        ),
        migrations.AddField(
            model_name='listing',
            name='has_topography',
            field=models.BooleanField(blank=True, null=True, verbose_name='Топосъёмка'),
        ),
        migrations.AddField(
            model_name='listing',
            name='has_water',
            field=models.BooleanField(blank=True, null=True, verbose_name='Водоснабжение'),
        ),
        migrations.AddField(
            model_name='listing',
            name='sale_reason',
            field=models.TextField(blank=True, verbose_name='Причина продажи'),
        ),
        migrations.AddField(
            model_name='listing',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='agency.buildingstage', verbose_name='Этап'),
        ),
        migrations.CreateModel(
            name='CuratorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата назначения')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='agency.agent', verbose_name='Куратор')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curator_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Кем назначен')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curator_history', to='agency.listing', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Назначение куратора',
                'verbose_name_plural': 'История кураторов',
                'ordering': ['-assigned_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='listing',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='listings', to='agency.document', verbose_name='Документы'),
        ),
        migrations.AddField(
            model_name='listing',
            name='furniture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='agency.furnitureoption', verbose_name='Остаётся мебель'),
        ),
        migrations.AddField(
            model_name='listing',
            name='heating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='agency.heating', verbose_name='Отопление'),
        ),
        migrations.AddField(
            model_name='listing',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='agency.line', verbose_name='Линия'),
        ),
        migrations.AddField(
            model_name='listing',
            name='payment_conditions',
            field=models.ManyToManyField(blank=True, related_name='listings', to='agency.paymentcondition', verbose_name='Какие условия рассматривает'),
        ),
        migrations.AddField(
            model_name='listing',
            name='sewerage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='agency.sewerage', verbose_name='Канализация'),
        ),
        migrations.AddField(
            model_name='listing',
            name='wall_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='agency.wallmaterial', verbose_name='Материал стен'),
        ),
    ]
