# Generated by Django 5.1.6 on 2026-08-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0004_seed_extra_dictionaries'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='is_manager',
            field=models.BooleanField(default=False, help_text='Может заводить агентов и править справочники', verbose_name='Руководитель'),
        ),
    ]
